import type { LessonInput } from "../../schema";
import { rspAt, vault, vaultSource } from "../../specimens/vault";

const row = (label: keyof typeof vault) => "disasm:" + vault[label];

/** Lesson 1.2, designed in docs/lessons/01-debugger-basics/02-controlling-execution.md. */
export const controllingExecution: LessonInput = {
  id: "m1.l2",
  module: 1,
  number: "1.2",
  title: "Controlling execution",
  mission:
    "Walk through main one instruction at a time. Step over the boring calls, step into the interesting one, and escape when you fall down a hole.",
  minutes: 12,
  recording: "vault.wrong",
  start: { at: vault.main, dump: "0000000140003200" },
  source: vaultSource,
  locks: { infobox: "1.4", callArgs: "3.1", command: "1.3" },
  console: true,
  steps: [
    {
      section: "beat",
      kind: "Choose",
      title: "Warm-up",
      say: "Quick check from last lesson: the highlighted line is `sub rsp,58`. Has it run yet?",
      spotlight: "disassembly",
      gate: {
        type: "choose",
        correct: "no",
        options: [
          { id: "yes", label: "Yes, it's highlighted because it just ran.", feedback: "The highlight marks the next instruction, the one `RIP` points at. It hasn't run yet." },
          { id: "no", label: "No, it runs when I step." },
        ],
      },
      success: "Right. Nothing has run yet. Let's step.",
    },
    {
      section: "beat",
      kind: "Key",
      title: "One instruction",
      say: "Press `F8` to run exactly one instruction. Keep an eye on the registers.",
      action: "Press `F8`",
      gate: { type: "key", key: "F8" },
      success:
        "`RIP` moved to the next line, and `RSP` dropped by `0x58`: `sub rsp,58` made room on the stack. A few flags changed too. Red means changed by the last step.",
      successHighlights: ["reg:RSP", "reg:RIP"],
      unlockKey: "F8",
    },
    {
      section: "beat",
      kind: "Predict",
      title: "Predict before stepping",
      say: "The next line is `lea rcx,qword ptr ds:[140003200]`. Before you press `F8`: which register will change, besides `RIP`? Click it.",
      action: "Click a register",
      spotlight: "registers",
      gate: {
        type: "click",
        accept: ["reg:RCX"],
        wrong: [
          { match: "reg:RIP", feedback: "`RIP` always changes. Which other register does this line write?" },
          { match: "reg:*", feedback: "The first operand is where the result goes. Read it again: `lea rcx`, ..." },
        ],
        fallback: "Click a register name in the registers pane.",
      },
      success: "Let's check. Press `F8`.",
    },
    {
      section: "beat",
      kind: "Key",
      title: "Check your prediction",
      say: "Press `F8` and see which register turns red.",
      action: "Press `F8`",
      gate: { type: "key", key: "F8" },
      success:
        "`RCX` is red and holds `140003200`. x64dbg even shows the text it points at: == PIRE VAULT ==. The line put the banner's address in `RCX`, ready to hand to puts. Module 3 explains why `RCX`.",
      successHighlights: ["reg:RCX"],
    },
    {
      section: "beat",
      kind: "Key",
      title: "Step over a call",
      say: "This line calls puts. `F8` runs the whole call and stops on the line after it. The console under the dump is still empty. Try it.",
      action: "Press `F8`",
      pulse: [row("main.puts")],
      gate: { type: "key", key: "F8" },
      success:
        "The console printed == PIRE VAULT ==, and `RIP` is on the next line. puts ran completely. You didn't see its code, and you didn't need to. Step over library calls you trust.",
    },
    {
      section: "beat",
      kind: "Key",
      title: "Load the next string",
      say: "One more `F8` loads the prompt into `RCX`. The line after it calls printf.",
      action: "Press `F8`",
      gate: { type: "key", key: "F8" },
      success: "`RCX` now points at \"Enter code: \". Next stop: the call to printf.",
    },
    {
      section: "beat",
      kind: "Key",
      title: "The rabbit hole",
      say: "`F7` steps into calls instead of over them. `RIP` is on `call <vault.printf>`. Press `F7` and see what happens.",
      action: "Press `F7`",
      pulse: [row("main.printf")],
      gate: { type: "key", key: "F7", wrong: [{ key: "F8", feedback: "`F8` would step over it. This time press `F7` to go inside." }] },
      success:
        "You're inside printf: C runtime code the compiler copied into vault.exe, which calls even deeper into ucrtbase.dll. Nobody wrote it for this lesson and you don't need to read it. Landing somewhere like this by accident happens to everyone.",
      unlockKey: "F7",
    },
    {
      section: "beat",
      kind: "Key",
      title: "Climbing out",
      say: "`Ctrl+F9` runs until this function is about to return.",
      action: "Press `Ctrl+F9`",
      gate: { type: "key", key: "Ctrl+F9" },
      success: "`RIP` is on printf's `ret`. You're still inside printf, one step from home.",
      unlockKey: "Ctrl+F9",
    },
    {
      section: "beat",
      kind: "Key",
      title: "Home",
      say: "Now press `F8` to run the `ret`.",
      action: "Press `F8`",
      gate: { type: "key", key: "F8" },
      success:
        "Escaped. You're back in main, on the line after the call, and the console shows Enter code:. Remember the pair: `Ctrl+F9` to reach the `ret`, `F8` to come home.",
    },
    {
      section: "beat",
      kind: "Key",
      title: "Run to cursor",
      say: "Stepping one line at a time gets slow. Click the `call <vault.check_code>` line (it's pulsing) and press `F4` to run until that line.",
      action: "Click the line, then press `F4`",
      pulse: [row("main.check")],
      gate: {
        type: "key",
        key: "F4",
        requires: "selection",
        target: row("main.check"),
        notReady: "Click the pulsing `call <vault.check_code>` line first, then press `F4`.",
      },
      success:
        "The console shows Enter code: hello. Everything in between ran, including fgets waiting for input. The recording typed hello for you. `RIP` is on the call.",
      unlockKey: "F4",
    },
    {
      section: "beat",
      kind: "Key",
      title: "Step into your own function",
      say: "This one is ours, and it decides whether the vault opens. Step into it.",
      action: "Press `F7`",
      source: "check_code",
      gate: { type: "key", key: "F7", wrong: [{ key: "F8", feedback: "`F8` would run check_code without stopping inside. Press `F7` to step in." }] },
      success:
        "You're inside check_code. Look at the top of the stack: a new row says return to vault.main+65. The call left that return address so check_code knows where to go back.",
      successHighlights: ["stack:" + rspAt("check_code")],
    },
    {
      section: "beat",
      kind: "Key",
      title: "Run",
      say: "`F9` lets the program run freely. There are no breakpoints, so it will run to the end.",
      action: "Press `F9`",
      gate: { type: "key", key: "F9" },
      success:
        "The console printed Access denied. and the status bar says the process stopped. `F9` means go. Next lesson, you'll put breakpoints in its way.",
      unlockKey: "F9",
    },
    {
      section: "checkpoint",
      kind: "Quiz",
      title: "Choose the key",
      say: "Pick the key for each situation.",
      gate: {
        type: "quiz",
        questions: [
          {
            prompt: "`RIP` is on call check_code and you want to see inside it.",
            options: [{ id: "F7", label: "`F7`" }, { id: "F8", label: "`F8`" }, { id: "F4", label: "`F4`" }, { id: "out", label: "`Ctrl+F9`, then `F8`" }],
            correct: "F7",
            feedback: "Into means see inside. Over means skip the inside.",
          },
          {
            prompt: "`RIP` is on call puts and you only care about what happens next in main.",
            options: [{ id: "F7", label: "`F7`" }, { id: "F8", label: "`F8`" }, { id: "F4", label: "`F4`" }, { id: "out", label: "`Ctrl+F9`, then `F8`" }],
            correct: "F8",
            feedback: "You don't want to see inside puts, so step over it.",
          },
          {
            prompt: "You're deep inside ucrtbase.dll by accident.",
            options: [{ id: "F7", label: "`F7`" }, { id: "F8", label: "`F8`" }, { id: "F4", label: "`F4`" }, { id: "out", label: "`Ctrl+F9`, then `F8`" }],
            correct: "out",
            feedback: "`Ctrl+F9` is the get-me-out key.",
          },
          {
            prompt: "You want to skip to a line 20 instructions down.",
            options: [{ id: "F7", label: "`F7`" }, { id: "F8", label: "`F8`" }, { id: "F4", label: "`F4`, after clicking the line" }, { id: "out", label: "`Ctrl+F9`, then `F8`" }],
            correct: "F4",
            feedback: "Pressing `F8` twenty times works, but there's a faster way.",
          },
        ],
      },
      hints: ["Into = see inside. Over = skip the inside.", "`Ctrl+F9` is the 'get me out' key."],
      success: "Four for four.",
    },
    {
      section: "checkpoint",
      kind: "Predict",
      title: "Which register?",
      say: "We're paused inside check_code on `mov eax,dword ptr ds:[<g_attempts>]`. Which register turns red after `F8`, besides `RIP`? Click it.",
      setup: { at: vault["check_code.load"], banner: "Paused inside check_code" },
      spotlight: "registers",
      gate: {
        type: "click",
        accept: ["reg:RAX"],
        wrong: [{ match: "reg:*", feedback: "The destination is the first operand. eax is the low half of `RAX`." }],
        fallback: "Click a register.",
      },
      success: "`RAX`. eax is its low 32 bits, and the destination is always the first operand.",
    },
    {
      section: "checkpoint",
      kind: "Choose",
      title: "Breakpoints win",
      say: "You press `F8` on a call, but there's a breakpoint inside the called function. Where do you stop?",
      gate: {
        type: "choose",
        correct: "inside",
        options: [
          { id: "after", label: "On the line after the call, as usual.", feedback: "Step over still stops at breakpoints. This catches people out in Lesson 1.3." },
          { id: "inside", label: "At the breakpoint inside the function." },
        ],
      },
      success: "Step over still runs every line of the call, so a breakpoint inside it still fires.",
    },
  ],
  tryIt: [
    "Load vault.exe and get to main: press F9 until you reach it, or press Ctrl+G, type main, and press F4 on its first line.",
    "Step over the puts call and watch the console window.",
    "F7 into the printf call, then escape with Ctrl+F9 and F8.",
    "Click call check_code, press F4, type a code in the console, then F7 into check_code.",
  ],
};
