import type { SourceFile } from "../../schema";

export const vaultSource: SourceFile = {
  name: "vault.c",
  code: [
    "#include <stdio.h>",
    "#include <string.h>",
    "#include <windows.h>",
    "",
    'static const char *SECRET = "opensesame";',
    "int g_attempts = 0;",
    "",
    "int check_code(const char *input)",
    "{",
    "    g_attempts++;",
    "    return strcmp(input, SECRET) == 0;",
    "}",
    "",
    "int main(void)",
    "{",
    "    char buffer[32];",
    "",
    '    puts("== PIRE VAULT ==");',
    '    printf("Enter code: ");',
    "    if (!fgets(buffer, sizeof buffer, stdin))",
    "        return 1;",
    '    buffer[strcspn(buffer, "\\n")] = 0;',
    "",
    "    if (check_code(buffer)) {",
    '        MessageBoxA(NULL, "Vault opened!", "PIRE", MB_OK);',
    "        return 0;",
    "    }",
    "",
    '    puts("Access denied.");',
    "    return 1;",
    "}",
  ].join("\n"),
  regions: {
    check_code: [8, 12],
    main: [14, 31],
    "main.puts": [18, 18],
  },
};
