import type { SourceFile } from "../../schema";

export const vault2Source: SourceFile = {
  name: "vault2.c",
  code: [
    "#include <stdio.h>",
    "#include <string.h>",
    "#include <windows.h>",
    "",
    'static const char *SECRET = "pirate42";',
    "int g_tries = 0;",
    "",
    "static int verify(const char *input)",
    "{",
    "    g_tries++;",
    "    if (g_tries > 3)",
    "        return 0;",
    "    return strcmp(input, SECRET) == 0;",
    "}",
    "",
    "int main(void)",
    "{",
    "    char buffer[32];",
    "",
    '    printf("Vault v2 - code: ");',
    "    if (!fgets(buffer, sizeof buffer, stdin))",
    "        return 1;",
    '    buffer[strcspn(buffer, "\\n")] = 0;',
    "",
    "    if (verify(buffer)) {",
    '        MessageBoxA(NULL, "You\'re in.", "PIRE", MB_OK);',
    "        return 0;",
    "    }",
    '    puts("Nope.");',
    "    return 1;",
    "}",
  ].join("\n"),
  regions: {
    verify: [8, 14],
    main: [16, 32],
    "main.prompt": [20, 20],
    "main.check": [25, 25],
    "main.messagebox": [26, 26],
    "verify.increment": [10, 10],
    "verify.limit": [11, 12],
    "verify.compare": [13, 13],
  },
};

