import type { SourceFile } from "../../schema";

export const callsSource: SourceFile = {
  name: "calls.c",
  code: [
    "#include <stdio.h>",
    "",
    "__declspec(noinline) int add(int a, int b)",
    "{",
    "    return a + b;",
    "}",
    "",
    "__declspec(noinline) long long sum6(int a, int b, int c, int d, int e, int f)",
    "{",
    "    return (long long)a + b + c + d + e + f;",
    "}",
    "",
    "__declspec(noinline) int scale(int x)",
    "{",
    "    int doubled = add(x, x);",
    "    return doubled * 3;",
    "}",
    "",
    "__declspec(noinline) double mix(int a, double b, int c, float d)",
    "{",
    "    return a * b + c * d;",
    "}",
    "",
    "__declspec(noinline) int shout(int times)",
    "{",
    "    int i;",
    "    for (i = 0; i < times; i++)",
    "        puts(\"PIRE!\");",
    "    return i;",
    "}",
    "",
    "int main(int argc, char **argv)",
    "{",
    "    int n = argc + 2;",
    "    (void)argv;",
    "",
    "    int r1 = add(n, 5);",
    "    long long r2 = sum6(1, 2, 3, 4, n, 6);",
    "    int r3 = scale(n);",
    "    double r4 = mix(n, 1.5, 2, 0.5f);",
    "    int r5 = shout(n);",
    "",
    "    printf(\"%d %lld %d %f %d\\n\", r1, r2, r3, r4, r5);",
    "    return 0;",
    "}",
  ].join("\n"),
  regions: {
    "add": [3, 6],
    "sum6": [8, 11],
    "scale": [13, 17],
    "mix": [19, 22],
    "shout": [24, 30],
    "main": [32, 45],
    "call.add": [37, 37],
    "call.sum6": [38, 38],
    "call.scale": [39, 39],
    "call.mix": [40, 40],
    "call.shout": [41, 41],
    "printf": [43, 43],
  },
};

